# Generated by Django 5.2.5 on 2025-10-28 06:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('converting', 'Converting to Images'), ('extracting', 'Extracting Data'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pdf_documents',
            },
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('image_file', models.ImageField(upload_to='pdf_pages/%Y/%m/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dpi', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='design_agent.pdfdocument')),
            ],
            options={
                'db_table': 'pdf_pages',
                'ordering': ['page_number'],
                'unique_together': {('pdf_document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('structured_data', models.JSONField(default=dict)),
                ('extraction_method', models.CharField(default='openai_gpt4_vision', max_length=50)),
                ('raw_response', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='design_agent.pdfpage')),
            ],
            options={
                'db_table': 'extractions',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('bathroom', 'Bathroom')], default='kitchen', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('8.50'), help_text='Tax rate %', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total including tax', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_pricings', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='design_agent.project')),
            ],
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_document', to='design_agent.project'),
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_preference', models.CharField(default='modern', max_length=50)),
                ('gemini_prompt', models.TextField()),
                ('image_file', models.ImageField(upload_to='renders/%Y/%m/')),
                ('generation_time', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('regeneration_reason', models.TextField(blank=True, default='')),
                ('parent_render', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='design_agent.render')),
                ('pdf_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='design_agent.pdfpage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='design_agent.project')),
            ],
            options={
                'db_table': 'renders',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation_type', models.CharField(choices=[('special_cabinet', 'Special Cabinet Note'), ('comment', 'General Comment'), ('change_request', 'Change Request')], max_length=20)),
                ('text', models.TextField()),
                ('sku_code', models.CharField(blank=True, max_length=100, null=True)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='design_agent.render')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SKUCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('cabinet', 'Cabinet'), ('tile', 'Tile'), ('appliance', 'Appliance')], db_index=True, max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('finish', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='sku_images/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price in USD', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sku_catalog',
                'indexes': [models.Index(fields=['category', 'width', 'height'], name='sku_catalog_categor_ed2f02_idx'), models.Index(fields=['category', 'subcategory'], name='sku_catalog_categor_8c3398_idx')],
            },
        ),
        migrations.CreateModel(
            name='SKUMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_text', models.CharField(max_length=100)),
                ('label_category', models.CharField(max_length=50)),
                ('match_score', models.FloatField()),
                ('position_data', models.JSONField(default=dict)),
                ('alternative_skus', models.JSONField(default=list)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_matches', to='design_agent.extraction')),
                ('matched_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_agent.skucatalog')),
            ],
            options={
                'db_table': 'sku_matches',
            },
        ),
        migrations.CreateModel(
            name='PricingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100)),
                ('sku_name', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit in USD', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount % (0-100)', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated discount in USD', max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='subtotal - discount_amount', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='design_agent.pricing')),
                ('sku_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_item', to='design_agent.skumatch')),
            ],
            options={
                'ordering': ['pricing', 'sku_code'],
            },
        ),
    ]
