# Generated by Django 5.2.5 on 2025-10-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricinglineitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='sku_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='sku_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design_agent.skumatch'),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='sku_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricinglineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
