# Generated by Django 5.2.5 on 2025-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_agent', '0002_alter_pricinglineitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfpage',
            name='preview_3d_image',
            field=models.ImageField(blank=True, help_text='Simple 3D preview for layout validation before final render', null=True, upload_to='3d_previews/%Y/%m/'),
        ),
    ]
