# design_agent/services/preview_3d_renderer.py
"""
3D Preview Renderer - Generate simple 3D layout previews
Focus: EXACT layout matching with labeled SKU codes
Output: Simple technical line drawing with depth indication
"""

import logging
import time
from typing import List, Optional
from io import BytesIO
from PIL import Image
from google import genai
from django.conf import settings
from django.core.files.base import ContentFile

from design_agent.models import PDFPage, Extraction, SKUMatch

logger = logging.getLogger('design_agent')


class Gemini3DPreviewRenderer:
    """
    Generate simple 3D layout previews from CAD elevations
    Purpose: Validate layout accuracy before photorealistic rendering
    """
    
    def __init__(self):
        self.client = genai.Client(api_key=settings.GEMINI_API_KEY)
        self.model_name = "gemini-2.5-flash-image"
        logger.info(f"✅ 3D Preview renderer initialized: {self.model_name}")
    
    def generate_3d_preview(
        self,
        pdf_page: PDFPage,
        extraction: Extraction,
        sku_matches: Optional[List[SKUMatch]] = None
    ) -> dict:
        """
        Generate 3D preview from CAD elevation
        
        Args:
            pdf_page: PDFPage object with CAD elevation image
            extraction: Extraction with layout data
            sku_matches: Optional SKU matches for labeling
        
        Returns:
            dict with:
                - success: bool
                - image_path: str (relative path to saved image)
                - generation_time: float
                - error: str (if failed)
        """
        view_type = extraction.structured_data.get('view_type', 'elevation')
        
        # Only process elevations
        if view_type.lower() == 'plan':
            logger.warning(f"⚠️ Skipping floor plan - only elevations supported")
            return {
                'success': False,
                'error': 'Floor plans not supported for 3D preview'
            }
        
        logger.info(f"🎨 Generating 3D preview for page {pdf_page.page_number}")
        
        try:
            start_time = time.time()
            
            # Load CAD elevation image
            with pdf_page.image_file.open('rb') as f:
                cad_layout = Image.open(BytesIO(f.read()))
            
            # Build SKU details for labeling
            sku_details = []
            if sku_matches:
                for match in sku_matches:
                    sku = match.matched_sku
                    sku_details.append({
                        'code': sku.code,
                        'name': sku.name,
                        'category': sku.category,
                        'width': float(sku.width) if sku.width else None,
                        'height': float(sku.height) if sku.height else None,
                        'depth': float(sku.depth) if sku.depth else None,
                    })
                logger.info(f"  📦 Including {len(sku_details)} SKU labels")
            
            # Build prompt for 3D preview
            prompt = self._build_3d_preview_prompt(
                extraction=extraction,
                sku_details=sku_details
            )
            
            # Generate 3D preview with Gemini
            logger.info("🖼️ Calling Gemini for 3D preview generation...")
            generated_image = self._generate_with_gemini(
                prompt=prompt,
                layout_image=cad_layout
            )
            
            if not generated_image:
                raise ValueError("No image generated by Gemini")
            
            # Save image
            image_io = BytesIO()
            generated_image.save(image_io, format='PNG')
            image_io.seek(0)
            
            filename = f"3d_preview_page_{pdf_page.page_number}_{int(time.time())}.png"
            pdf_page.preview_3d_image.save(filename, ContentFile(image_io.read()), save=False)
            pdf_page.save()
            
            generation_time = time.time() - start_time
            
            logger.info(f"✅ 3D preview generated in {generation_time:.2f}s")
            logger.info(f"   Saved to: {pdf_page.preview_3d_image.url}")
            
            return {
                'success': True,
                'image_path': pdf_page.preview_3d_image.url,
                'generation_time': generation_time,
                'page_number': pdf_page.page_number
            }
            
        except Exception as e:
            logger.error(f"❌ 3D preview generation failed: {str(e)}")
            return {
                'success': False,
                'error': str(e)
            }
    
    def _generate_with_gemini(
        self,
        prompt: str,
        layout_image: Image.Image
    ) -> Image.Image:
        """
        Call Gemini 2.5 Flash Image to generate 3D preview
        """
        try:
            # Build content array
            content = [prompt, layout_image]
            
            # Call Gemini
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=content
            )
            
            # Extract image
            for part in response.candidates[0].content.parts:
                if part.inline_data is not None:
                    image_bytes = part.inline_data.data
                    generated_image = Image.open(BytesIO(image_bytes))
                    logger.info("✅ 3D preview image generated successfully")
                    return generated_image
            
            raise ValueError("No image found in Gemini response")
            
        except Exception as e:
            logger.error(f"❌ Gemini generation failed: {e}")
            raise
    
    def _build_3d_preview_prompt(self, extraction: Extraction, sku_details: List[dict]) -> str:
        view_type = extraction.structured_data.get('view_type', 'elevation')
        items = extraction.structured_data.get('items', [])

        sku_section = ""
        if sku_details:
            sku_list = []
            for sku in sku_details:
                desc = f"- **{sku['code']}**: {sku['name']}"
                if sku['width'] or sku['height'] or sku['depth']:
                    dims = []
                    if sku['width']:
                        dims.append(f"{sku['width']}\"W")
                    if sku['height']:
                        dims.append(f"{sku['height']}\"H")
                    if sku['depth']:
                        dims.append(f"{sku['depth']}\"D")
                    desc += f" ({' × '.join(dims)})"
                sku_list.append(desc)
            sku_section = f"""
    **COMPONENTS TO LABEL ({len(sku_list)} items):**
    {chr(10).join(sku_list)}

    ⚠️ Each component must be labeled with its SKU code.
    """

        prompt = f"""Generate a TECHNICAL 3D PERSPECTIVE VIEW of this kitchen elevation.

    **OBJECTIVE:** Produce a simple but dimensionally ACCURATE 3D preview that clearly shows depth, spacing, and alignment.

    **VIEW ANGLE:**
    - Slight horizontal angle (~15–20° from front)
    - Very small vertical tilt (~5–10° downward)
    - Camera at standard eye-level (~5 feet above floor)
    - Keep proportions and alignment exact — no distortion
    - Maintain elevation reference (front wall layout remains primary)

    **STYLE GUIDELINES:**
    1. **Pure White Environment**
    - Background and floor should be matte white or light gray
    - No visible environment, shadows, or reflections

    2. **Neutral Lighting**
    - Soft, even lighting — no dramatic contrast
    - Focus on form and spacing, not materials

    3. **Simple Depth Indication**
    - Use very light gray faces to show cabinet depth
    - Maintain clean black outlines for edges
    - NO textures, wood grain, or realism

    4. **Labeling**
    - Each SKU labeled in clean sans-serif black text
    - Labels placed clearly with minimal overlap
    - Use thin connectors/arrows if needed

    5. **Geometric Precision**
    - Cabinet widths, heights, and spacing must exactly match CAD drawing
    - Wall and base cabinet alignment must remain perfectly level
    - Appliances correctly proportioned

    6. **Perspective Control**
    - Subtle 3D angle, just enough to show side depth of cabinets
    - Keep verticals nearly parallel (architectural camera, not wide angle)
    - Avoid fish-eye or artistic lens distortion

    ---

    {sku_section}

    **DO NOT INCLUDE:**
    - Colors, materials, shadows, or lighting effects
    - Background elements (windows, walls, people)
    - Realistic rendering, textures, or reflections

    ---

    **OUTPUT GOAL:**
    A clean, dimensionally accurate, angled 3D preview of the elevation drawing suitable for layout validation before photorealistic rendering.

    **VERIFY:**
    ✓ All {len(items)} elements present and correctly positioned  
    ✓ Depth visible and consistent  
    ✓ Labels clear and aligned  
    ✓ Perspective subtle but readable  
    ✓ White background, clean black lines  
    ✓ Perfect scale and geometry match
    """

        return prompt



# design_agent/services/preview_3d_renderer.py
# """
# 3D Preview Renderer - Generate simple 3D layout previews
# Focus: EXACT layout matching with labeled SKU codes
# Output: Simple technical line drawing with depth indication
# """

# import logging
# import time
# from typing import List, Optional
# from io import BytesIO
# from PIL import Image
# from google import genai
# from django.conf import settings
# from django.core.files.base import ContentFile

# from design_agent.models import PDFPage, Extraction, SKUMatch

# logger = logging.getLogger('design_agent')


# class Gemini3DPreviewRenderer:
#     """
#     Generate simple 3D layout previews from CAD elevations
#     Purpose: Validate layout accuracy before photorealistic rendering
#     """
    
#     def __init__(self):
#         self.client = genai.Client(api_key=settings.GEMINI_API_KEY)
#         self.model_name = "gemini-2.5-flash-image"
#         logger.info(f"✅ 3D Preview renderer initialized: {self.model_name}")
    
#     def generate_3d_preview(
#         self,
#         pdf_page: PDFPage,
#         extraction: Extraction,
#         sku_matches: Optional[List[SKUMatch]] = None
#     ) -> dict:
#         """
#         Generate 3D preview from CAD elevation
        
#         Args:
#             pdf_page: PDFPage object with CAD elevation image
#             extraction: Extraction with layout data
#             sku_matches: Optional SKU matches for labeling
        
#         Returns:
#             dict with:
#                 - success: bool
#                 - image_path: str (relative path to saved image)
#                 - generation_time: float
#                 - error: str (if failed)
#         """
#         view_type = extraction.structured_data.get('view_type', 'elevation')
        
#         # Only process elevations
#         if view_type.lower() == 'plan':
#             logger.warning(f"⚠️ Skipping floor plan - only elevations supported")
#             return {
#                 'success': False,
#                 'error': 'Floor plans not supported for 3D preview'
#             }
        
#         logger.info(f"🎨 Generating 3D preview for page {pdf_page.page_number}")
        
#         try:
#             start_time = time.time()
            
#             # Load CAD elevation image
#             with pdf_page.image_file.open('rb') as f:
#                 cad_layout = Image.open(BytesIO(f.read()))
            
#             # Build SKU details for labeling
#             sku_details = []
#             if sku_matches:
#                 for match in sku_matches:
#                     sku = match.matched_sku
#                     sku_details.append({
#                         'code': sku.code,
#                         'name': sku.name,
#                         'category': sku.category,
#                         'width': float(sku.width) if sku.width else None,
#                         'height': float(sku.height) if sku.height else None,
#                         'depth': float(sku.depth) if sku.depth else None,
#                     })
#                 logger.info(f"  📦 Including {len(sku_details)} SKU labels")
            
#             # Build prompt for 3D preview
#             prompt = self._build_3d_preview_prompt(
#                 extraction=extraction,
#                 sku_details=sku_details
#             )
            
#             # Generate 3D preview with Gemini
#             logger.info("🖼️ Calling Gemini for 3D preview generation...")
#             generated_image = self._generate_with_gemini(
#                 prompt=prompt,
#                 layout_image=cad_layout
#             )
            
#             if not generated_image:
#                 raise ValueError("No image generated by Gemini")
            
#             # Save image
#             image_io = BytesIO()
#             generated_image.save(image_io, format='PNG')
#             image_io.seek(0)
            
#             filename = f"3d_preview_page_{pdf_page.page_number}_{int(time.time())}.png"
#             pdf_page.preview_3d_image.save(filename, ContentFile(image_io.read()), save=False)
#             pdf_page.save()
            
#             generation_time = time.time() - start_time
            
#             logger.info(f"✅ 3D preview generated in {generation_time:.2f}s")
#             logger.info(f"   Saved to: {pdf_page.preview_3d_image.url}")
            
#             return {
#                 'success': True,
#                 'image_path': pdf_page.preview_3d_image.url,
#                 'generation_time': generation_time,
#                 'page_number': pdf_page.page_number
#             }
            
#         except Exception as e:
#             logger.error(f"❌ 3D preview generation failed: {str(e)}")
#             return {
#                 'success': False,
#                 'error': str(e)
#             }
    
#     def _generate_with_gemini(
#         self,
#         prompt: str,
#         layout_image: Image.Image
#     ) -> Image.Image:
#         """
#         Call Gemini 2.5 Flash Image to generate 3D preview
#         """
#         try:
#             # Build content array
#             content = [prompt, layout_image]
            
#             # Call Gemini
#             response = self.client.models.generate_content(
#                 model=self.model_name,
#                 contents=content
#             )
            
#             # Extract image
#             for part in response.candidates[0].content.parts:
#                 if part.inline_data is not None:
#                     image_bytes = part.inline_data.data
#                     generated_image = Image.open(BytesIO(image_bytes))
#                     logger.info("✅ 3D preview image generated successfully")
#                     return generated_image
            
#             raise ValueError("No image found in Gemini response")
            
#         except Exception as e:
#             logger.error(f"❌ Gemini generation failed: {e}")
#             raise
    
#     def _build_3d_preview_prompt(
#         self,
#         extraction: Extraction,
#         sku_details: List[dict]
#     ) -> str:
#         """
#         Build prompt for simple 3D preview generation
#         Focus: EXACT geometric accuracy with minimal styling
#         """
#         view_type = extraction.structured_data.get('view_type', 'elevation')
#         items = extraction.structured_data.get('items', [])
        
#         # Build SKU list for reference
#         sku_section = ""
#         if sku_details:
#             sku_list = []
#             for sku in sku_details:
#                 desc = f"- **{sku['code']}**: {sku['name']}"
#                 if sku['width'] or sku['height'] or sku['depth']:
#                     dims = []
#                     if sku['width']:
#                         dims.append(f"{sku['width']}\"W")
#                     if sku['height']:
#                         dims.append(f"{sku['height']}\"H")
#                     if sku['depth']:
#                         dims.append(f"{sku['depth']}\"D")
#                     desc += f" ({' × '.join(dims)})"
#                 sku_list.append(desc)
            
#             sku_section = f"""
# **COMPONENTS TO LABEL ({len(sku_list)} items):**
# {chr(10).join(sku_list)}

# ⚠️ CRITICAL: Each component must be clearly labeled with its SKU code."""

#         prompt = f"""Generate a TECHNICAL 3D LINE DRAWING of this kitchen/bathroom elevation for layout validation.

# **CRITICAL: THIS IS A TECHNICAL DRAWING, NOT A RENDER**

# **PRIMARY OBJECTIVE:** Create a simple line drawing showing the 2D elevation in 3D perspective with PERFECT geometric accuracy.

# **STYLE REQUIREMENTS - EXTREMELY IMPORTANT:**

# 1. **PURE WHITE BACKGROUND**
#    - Absolutely plain white background (#FFFFFF)
#    - No shadows on background
#    - No ambient occlusion
#    - No background elements whatsoever

# 2. **BLACK LINE DRAWING ONLY:**
#    - Use ONLY black lines (#000000) to define edges
#    - Line weight: Thin to medium (1-3px)
#    - NO fills, NO colors, NO shading, NO gradients
#    - Think: Technical blueprint or CAD wireframe with depth

# 3. **MINIMAL SHADING (ONLY IF ABSOLUTELY NECESSARY):**
#    - If depth needs to be shown, use VERY LIGHT GRAY FILLS (#F5F5F5 to #E8E8E8)
#    - Front faces: White or very light gray
#    - Side faces (depth): Slightly darker gray to show recession
#    - NO realistic shading, lighting, or shadows
#    - Keep it FLAT and DIAGRAMMATIC

# 4. **NO DECORATIVE ELEMENTS:**
#    - No handles, knobs, or hardware details
#    - No texture or material indication
#    - No lighting effects
#    - No styling whatsoever
#    - Pure geometric forms only

# ---

# **INPUT:** Technical CAD elevation drawing (2D front view)
# **OUTPUT:** Simple 3D line drawing showing the same layout with subtle depth indication

# **LAYOUT TYPE:** {view_type.upper()} VIEW

# {sku_section}

# ---

# **GEOMETRIC ACCURACY REQUIREMENTS:**

# 1. **PIXEL-PERFECT LAYOUT MATCHING:**
#    - Every element position must match the CAD drawing EXACTLY
#    - All dimensions preserved with <0.5% deviation
#    - Maintain precise spacing between all elements
#    - Horizontal and vertical alignments must be perfect

# 2. **3D PERSPECTIVE (CRITICAL - FRONT VIEW ONLY):**
#    - **CAMERA POSITION: Directly centered in front of the elevation, eye level**
#    - **DO NOT rotate or angle the view to the left or right**
#    - View should be almost orthographic with MINIMAL perspective distortion
#    - Think: Standing directly in front of the kitchen looking straight at it
#    - Elevation: Viewer positioned at eye level (5-6 feet high), centered
#    - Show depth ONLY by drawing the side panels of cabinets (not by rotating the view)
#    - Depth shown through parallel lines, NOT through camera angle
#    - FORBIDDEN: Side views, angled views, corner views, isometric views that show too much side

# 3. **HOW TO SHOW DEPTH WITHOUT ROTATING CAMERA:**
#    - Draw cabinet boxes as rectangles (front face)
#    - Add thin side panels visible on left/right edges (showing 12-24" depth)
#    - Countertop shows slight thickness edge
#    - NO rotation of the entire view
#    - The 3D effect comes from drawing the edges, not from changing camera angle
#    - Draw cabinet boxes as simple rectangles with depth
#    - Show doors/drawers as rectangular outlines
#    - Appliances as simplified geometric shapes
#    - All edges clearly defined with black lines
#    - No hidden line removal (show all edges for clarity)

# 4. **SKU CODE LABELS:**
#    - Position labels clearly near each component
#    - Label format: Simple black text on white background
#    - OR: White text in black rectangle box
#    - Connected with thin black lines/arrows if needed
#    - Font: Clean, sans-serif, readable size
#    - Place labels outside the drawing area when possible to avoid clutter

# 5. **DEPTH REPRESENTATION:**
#    - Base cabinets: 24" deep (show side panel)
#    - Wall cabinets: 12-14" deep (show side panel)
#    - Countertop: Show front edge and slight depth
#    - All depth shown with simple parallel lines
#    - NO perspective distortion of depth

# ---

# **ELEMENT POSITIONING (MUST MATCH CAD EXACTLY):**

# - **Base Cabinets:** On floor level, aligned in continuous row
# - **Wall Cabinets:** Mounted above base cabinets with gap (typically 18")
# - **Appliances:** Integrated at exact positions from CAD
# - **Countertop:** Continuous horizontal surface connecting all base units
# - **Vertical Alignment:** Cabinet edges stack perfectly
# - **Horizontal Alignment:** All base tops level, all wall bottoms level

# ---

# **VERIFICATION CHECKLIST:**
# □ Layout matches CAD drawing exactly (verify each element)
# □ All {len(items)} items from CAD are present
# □ All dimensions and proportions preserved
# □ White background with black line drawing only
# □ Minimal shading (light gray only if needed)
# □ All SKU codes clearly labeled and readable
# □ 3D depth visible but not exaggerated or stylized
# □ NO colors, NO textures, NO realistic materials
# □ NO shadows, lighting effects, or decorative elements

# ---

# **CRITICAL OUTPUT SPECIFICATIONS:**

# **ALLOWED:**
# - Black lines (#000000) for all edges and outlines
# - White background (#FFFFFF)
# - Very light gray fills (#F5F5F5 to #E8E8E8) ONLY for showing depth
# - Black text labels for SKU codes
# - Simple connecting lines/arrows for labels

# **ABSOLUTELY FORBIDDEN:**
# - Colors (beige, brown, gray cabinets, etc.)
# - Textures (wood grain, tile patterns, etc.)
# - Shadows or lighting effects
# - Gradients or shading (except minimal depth indication)
# - Decorative elements (handles, knobs, trim)
# - Realistic materials
# - Background elements
# - Complex perspective or dramatic angles

# ---

# **EXAMPLE VISUAL STYLE:**
# Think of this exactly like:
# - A CAD wireframe export with light gray depth fill
# - An architect's technical line drawing with subtle 3D
# - A blueprint elevation view with depth indication (NOT isometric)
# - Engineering diagram showing front assembly view

# **CAMERA ANGLE REFERENCE:**
# - CORRECT: Straight-on front view (like looking at a wall head-on)
# - CORRECT: Slight elevation (viewer's eyes at countertop height)
# - WRONG: Angled views showing side walls
# - WRONG: Isometric views with 45° rotation
# - WRONG: Corner views showing multiple walls

# **WHAT THIS IS:** Technical validation drawing with front-facing view
# **WHAT THIS IS NOT:** Artistic rendering, sketch, or 3D walkthrough perspective

# ---

# **ABSOLUTELY CRITICAL:**
# - EXACT geometric match to CAD elevation (this is the ONLY priority)
# - Pure line drawing aesthetic (black lines on white)
# - **FRONT-FACING VIEW ONLY - No side angles, no rotation, no isometric distortion**
# - Camera positioned directly in front, centered, eye level
# - All SKU codes must be clearly labeled
# - This is a MEASUREMENT/VALIDATION tool, not a presentation image
# - Depth shown through parallel lines on cabinet sides, NOT through camera rotation

# Generate a clean, accurate, labeled technical 3D line drawing suitable for layout validation."""

#         return prompt